package com.search.extension;
import org.junit.jupiter.api.*;import static org.junit.jupiter.api.Assertions.*;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.test.web.client.TestRestTemplate;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.test.context.DynamicPropertySource;import org.springframework.test.context.DynamicPropertyRegistry;import org.springframework.http.ResponseEntity;import com.sun.net.httpserver.HttpServer;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.concurrent.atomic.AtomicBoolean;import com.search.extension.apiSearch.adapter.persistence.SearchKeywordHistoryJpaRepository;import com.search.extension.scheduledTask.UpdatePopularKeywordTask;import io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry;
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"spring.datasource.url=jdbc:h2:mem:full-http;DB_CLOSE_DELAY=-1","search.scheduler.enabled=false"})
class NativeHttpContractTest {
 static HttpServer providers;static AtomicBoolean kakaoDown=new AtomicBoolean(false),naverDown=new AtomicBoolean(false);
 static {try{providers=HttpServer.create(new InetSocketAddress("127.0.0.1",0),0);providers.createContext("/v2/search/blog",ex->{boolean fail=kakaoDown.get();byte[] body=(fail?"{}":"{\"meta\":{\"total_count\":1,\"pageable_count\":1,\"is_end\":true},\"documents\":[{\"title\":\"Local native result\",\"contents\":\"Synthetic\",\"url\":\"\",\"blogname\":\"Local\",\"thumbnail\":\"\",\"datetime\":\"2026-09-26\"}]}").getBytes(StandardCharsets.UTF_8);ex.getResponseHeaders().set("Content-Type","application/json");ex.sendResponseHeaders(fail?503:200,body.length);ex.getResponseBody().write(body);ex.close();});providers.createContext("/v1/search/blog",ex->{boolean fail=naverDown.get();byte[] body=(fail?"{}":"{\"lastBuildDate\":\"Synthetic\",\"total\":1,\"start\":1,\"display\":1,\"items\":[{\"title\":\"Local fallback\",\"link\":\"\",\"description\":\"Synthetic\",\"bloggername\":\"Local\",\"bloggerlink\":\"\",\"postdate\":\"20260926\"}]}").getBytes(StandardCharsets.UTF_8);ex.getResponseHeaders().set("Content-Type","application/json");ex.sendResponseHeaders(fail?503:200,body.length);ex.getResponseBody().write(body);ex.close();});providers.start();}catch(Exception e){throw new ExceptionInInitializerError(e);}}
 @DynamicPropertySource static void config(DynamicPropertyRegistry r){r.add("kakao.api.base-url",()->"http://127.0.0.1:"+providers.getAddress().getPort());r.add("naver.api.base-url",()->"http://127.0.0.1:"+providers.getAddress().getPort());}
 @Autowired TestRestTemplate http;@Autowired SearchKeywordHistoryJpaRepository history;@Autowired UpdatePopularKeywordTask aggregate;@Autowired CircuitBreakerRegistry breakers;
 @BeforeEach void reset(){kakaoDown.set(false);naverDown.set(false);breakers.getAllCircuitBreakers().forEach(b->b.reset());}
 @AfterAll static void stop(){providers.stop(0);}
 @Test void actualEndpointsPersistAndServeSameOriginLiveConsole(){long before=history.count();ResponseEntity<String> result=http.getForEntity("/search?query=native-http",String.class);assertEquals(200,result.getStatusCode().value());assertTrue(result.getBody().contains("Local native result"));assertEquals(before+1,history.count());aggregate.updatePopularKeywordDatabase();ResponseEntity<String> popular=http.getForEntity("/popularKeyword",String.class);assertEquals(200,popular.getStatusCode().value());assertTrue(popular.getBody().contains("native-http"));ResponseEntity<String> page=http.getForEntity("/console/live.html",String.class);assertEquals(200,page.getStatusCode().value());assertTrue(page.getBody().contains("data-mode=\"live\""));assertTrue(page.getBody().contains("connect-src 'self'"));}
 @Test void fallbackAndLegacyFailureEnvelopesStayExact(){kakaoDown.set(true);ResponseEntity<String> fallback=http.getForEntity("/search?query=fallback-http",String.class);assertEquals(200,fallback.getStatusCode().value());assertTrue(fallback.getBody().contains("Local fallback"));naverDown.set(true);assertEquals(501,http.getForEntity("/search?query=both-down",String.class).getStatusCode().value());assertEquals(401,http.getForEntity("/search?query=invalid&sort=wrong",String.class).getStatusCode().value());assertEquals(402,http.getForEntity("/search?query=invalid&page=0",String.class).getStatusCode().value());}
}
