package com.search.extension;
import org.junit.jupiter.api.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;import static org.mockito.ArgumentMatchers.*;import java.util.*;import java.util.concurrent.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.test.mock.mockito.MockBean;import org.springframework.boot.test.mock.mockito.SpyBean;import org.springframework.test.annotation.DirtiesContext;import org.springframework.data.domain.PageRequest;import org.springframework.aop.support.AopUtils;import com.search.extension.apiSearch.application.port.*;import com.search.extension.apiSearch.adapter.persistence.*;import com.search.extension.scheduledTask.UpdatePopularKeywordTask;
@SpringBootTest(properties={"spring.datasource.url=jdbc:h2:mem:aggregate-isolated;DB_CLOSE_DELAY=-1","search.scheduler.enabled=false"}) @DirtiesContext(classMode=DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
class PopularAggregationTest {
 @Autowired ApiBlogSearchService service;@Autowired UpdatePopularKeywordTask task;@Autowired SearchKeywordHistoryJpaRepository history;@SpyBean PopularKeywordJpaRepository popular;@MockBean(name="kakaoApi") KakaoBlogSearchService kakao;
 @BeforeEach void setup(){when(kakao.getApiSearchResults(anyString(),anyString(),any())).thenReturn(Map.of("currentPage",1));}
 @Test void concurrentSearchesAndSnapshotReadersNeverSeeDeleteGap()throws Exception{assertTrue(AopUtils.isAopProxy(task));service.getApiSearchResults("baseline","accuracy",PageRequest.of(1,10));task.updatePopularKeywordDatabase();ExecutorService pool=Executors.newFixedThreadPool(6);try{List<Future<?>> jobs=new ArrayList<>();for(int i=0;i<30;i++)jobs.add(pool.submit(()->service.getApiSearchResults("shared","accuracy",PageRequest.of(1,10))));for(int i=0;i<10;i++){task.updatePopularKeywordDatabase();assertFalse(service.getPopularKeyword().isEmpty());}for(Future<?> job:jobs)job.get();task.updatePopularKeywordDatabase();assertEquals(31,history.count());assertEquals(30,service.getPopularKeyword().stream().filter(k->k.getKeyword().equals("shared")).findFirst().orElseThrow().getCount());}finally{pool.shutdownNow();}}
 @Test void failedReplacementRollsBackThePreviousSnapshot(){service.getApiSearchResults("baseline","accuracy",PageRequest.of(1,10));task.updatePopularKeywordDatabase();doThrow(new org.springframework.dao.DataAccessResourceFailureException("synthetic write failure")).when(popular).saveAll(any());assertThrows(RuntimeException.class,()->task.updatePopularKeywordDatabase());assertEquals(1,popular.count());assertEquals("baseline",service.getPopularKeyword().get(0).getKeyword());}
}
